org: bencoderus
app: rate-serverless
service: rate-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 512

functions:
  api:
    handler: src/handler.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-offline
