org: bencoderus
app: aws-node-express-api-project
service: aws-node-express-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 512

functions:
  api:
    handler: src/handler.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-offline
